services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: backend-test:latest
    container_name: backend-app
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    image: frontend-test:latest
    container_name: frontend-app
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
